name: Build PeekXtract

on:
  push:
    branches:
      - main
    paths:
      - 'src/peekxtract.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from Python file
        id: version
        shell: bash
        run: |
          VERSION=$(grep "^__version__" src/peekxtract.py | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building PeekXtract v$VERSION"
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests
      
      - name: Build PeekXtract executable
        run: pyinstaller --onefile --clean --optimize 2 --name PeekXtract src/peekxtract.py
      
      - name: Upload PeekXtract for Windows
        uses: actions/upload-artifact@v4
        with:
          name: PeekXtract-Windows-v${{ steps.version.outputs.VERSION }}
          path: dist/PeekXtract.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from Python file
        id: version
        run: |
          VERSION=$(grep "^__version__" src/peekxtract.py | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building PeekXtract v$VERSION"
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests
      
      - name: Build PeekXtract executable
        run: pyinstaller --onefile --clean --optimize 2 --name PeekXtract src/peekxtract.py
      
      - name: Upload PeekXtract for Linux
        uses: actions/upload-artifact@v4
        with:
          name: PeekXtract-Linux-v${{ steps.version.outputs.VERSION }}
          path: dist/PeekXtract
